apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: spinnaker-operator
spec:
  spinnakerConfig:
    config:
      version: 1.17.1
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: spinbucker
          rootFolder: front50
          endpoint: http://minio.ns-minio:9000
          accessKeyId: AKIAIOSFODNN7EXAMPLE
          secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  expose:
    type: service
    service:
      type: LoadBalancer
